### ISSUE TITLE
more data

### ISSUE THREAD

**Issue by WHZack** [fcalesella/neurohab#1]
hey fcalesella, could u plz provide one example .nii data for run, it will help a lot!

**Comment by fcalesella** [comment]
Hi WHZack!
I cannot share data, due to privacy concerns.
However, I included a test folder in which you can find a script to simulate some random data, and another example to run on the simulated data. 
Already generated data and outputs are in the test_data and test_output folders.

**Comment by WHZack** [comment]
thanks fcalesella, it did help!
